# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qisoval
                                 A QGIS plugin
 Carte isochrone/isodistance - IGN Geoportail
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-05-05
        copyright            : (C) 2020 by SIGéal
        email                : sigeal@sigeal.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load qisoval class from file qisoval.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qisoval import qisoval
    return qisoval(iface)
