# -*- coding: utf-8 -*-
"""
/***************************************************************************
 qisoval
                                 A QGIS plugin
 Carte isochrone/isodistance - IGN Geoportail
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-05-05
        git sha              : $Format:%H$
        copyright            : (C) 2020 by SIGéal
        email                : sigeal@sigeal.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import Qt, QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

import sys
import requests
from xml.etree import ElementTree
from qgis.core import QgsVectorLayer, QgsProject, QgsRenderContext, QgsSimpleFillSymbolLayer, QgsSettings
from qgis.PyQt.QtGui import QColor

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dockwidget
from .qisoval_dock import qIsovalDock
import os.path


class qisoval:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'qisoval_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&QIsoVal')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('qisoval', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/qisoval/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'QIsoVal'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dock = qIsovalDock()
            self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.dock)
        self.initDock()

    def initDock(self):
        """Dock widget init"""

        # btnLaunch action
        self.dock.btnLaunch.clicked.connect(
            self.btnLaunchAction)

    def btnLaunchAction(self):
        """btnLaunch action"""

        # Paramètres du web service IGN de calcul d'isochrone
        x = 2.424626
        y = 48.845793
        location = '{},{}'.format(x, y)
        method = 'time'  # time distance
        graphname = 'Voiture'  # Voiture Pieton
        time = 90 * 60  # si method time
        distance = 100000 # si method distance
        holes = False  # True False
        smoothing = True  # True False
        epsg = 4326
        apiKey = 'choisirgeoportail'

        # Paramètres de symbologie
        fillRed = QColor(251, 154, 153)
        fillBlue = QColor(166, 206, 227)
        fillGreen = QColor(178, 223, 138)
        fillColor = fillGreen
        strokeRed = QColor(251, 154, 153)
        strokeBlue = QColor(31, 120, 180)
        strokeGreen = QColor(51, 160, 44)
        strokeColor = strokeGreen
        borderWidth = 0.4
        opacity = 0.7

        # url du service de calcul
        if method == 'time':
            param = 'time={}'.format(time)
        elif method == 'distance':
            param = 'distance={}'.format(distance)

        url = '''
            https://wxs.ign.fr/{}/isochrone/isochrone.xml?location={}&method={}&graphName={}&exclusions=&{}&holes={}&smoothing={}
        '''.format(apiKey, location, method, graphname, param, holes, smoothing)
        print(url)

        # Récupération du User-Agent QGIS
        s = QgsSettings()
        userAgent = s.value('/qgis/networkAndProxy/userAgent', 'Mozilla/5.0')
        headers = {'User-Agent': userAgent}

        # Appel du service
        #xmlResponse = requests.get(url, timeout=10)
        xmlResponse = requests.get(url, headers=headers)
        print(xmlResponse)

        # Décodage de la réponse et récupération de la géométrie
        root = ElementTree.fromstring(xmlResponse.content)
        wktGeometry = root.find('wktGeometry')
        #print(wktGeometry.text)
        if wktGeometry is not None:

            # Construction de la requête sql
            sql = '''
                select st_geomfromtext('{}', {}) geom
            '''.format(wktGeometry.text, epsg)
            #print(sql)

            # Construction de la couche virtuelle
            if method == 'time':
                libLayer = '{}_{}_minutes'.format(graphname, int(time / 60))
            elif method == 'distance':
                libLayer = '{}_{}_kilometres'.format(graphname, int(distance / 1000))
            vLayer = QgsVectorLayer('?query={}'.format(sql), libLayer, 'virtual')
            #symbol = QgsFillSymbol()
            #symbol.setColor(fillColor)
            symbolLayer = QgsSimpleFillSymbolLayer()
            symbolLayer.setStrokeWidth(borderWidth)
            symbolLayer.setStrokeColor(strokeColor)
            symbolLayer.setFillColor(fillColor)
            vLayer.renderer().symbols(
                QgsRenderContext())[0].changeSymbolLayer(0, symbolLayer)
            vLayer.setOpacity(opacity)  # Pour essai
            QgsProject.instance().addMapLayer(vLayer)

        else:
            print('Échec de l\'appel du service')


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&QIsoVal'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        """
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dock = qIsovalDock()
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dock)
        """

        if self.dock.isVisible():
            self.dock.hide()
        else:
            self.dock.show()

        """
        # show the dialog
        self.dock.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
        """
