# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qisoval_dock_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QIsoValDockBase(object):
    def setupUi(self, QIsoValDockBase):
        QIsoValDockBase.setObjectName("QIsoValDockBase")
        QIsoValDockBase.resize(344, 704)
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edtAdd = QtWidgets.QLineEdit(self.groupBox)
        self.edtAdd.setObjectName("edtAdd")
        self.horizontalLayout.addWidget(self.edtAdd)
        self.btnPos = QtWidgets.QPushButton(self.groupBox)
        self.btnPos.setObjectName("btnPos")
        self.horizontalLayout.addWidget(self.btnPos)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.rbnIsochron = QtWidgets.QRadioButton(self.groupBox)
        self.rbnIsochron.setObjectName("rbnIsochron")
        self.grpIsoType = QtWidgets.QButtonGroup(QIsoValDockBase)
        self.grpIsoType.setObjectName("grpIsoType")
        self.grpIsoType.addButton(self.rbnIsochron)
        self.horizontalLayout_2.addWidget(self.rbnIsochron)
        self.rbnIsoDistance = QtWidgets.QRadioButton(self.groupBox)
        self.rbnIsoDistance.setObjectName("rbnIsoDistance")
        self.grpIsoType.addButton(self.rbnIsoDistance)
        self.horizontalLayout_2.addWidget(self.rbnIsoDistance)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.sbxHour = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbxHour.setObjectName("sbxHour")
        self.horizontalLayout_3.addWidget(self.sbxHour)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.sbxMinute = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbxMinute.setObjectName("sbxMinute")
        self.horizontalLayout_3.addWidget(self.sbxMinute)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.sbxKilometer = QtWidgets.QSpinBox(self.groupBox_3)
        self.sbxKilometer.setObjectName("sbxKilometer")
        self.horizontalLayout_3.addWidget(self.sbxKilometer)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.rbnWalk = QtWidgets.QRadioButton(self.groupBox_5)
        self.rbnWalk.setObjectName("rbnWalk")
        self.grpIsoMode = QtWidgets.QButtonGroup(QIsoValDockBase)
        self.grpIsoMode.setObjectName("grpIsoMode")
        self.grpIsoMode.addButton(self.rbnWalk)
        self.horizontalLayout_5.addWidget(self.rbnWalk)
        self.rbnDrive = QtWidgets.QRadioButton(self.groupBox_5)
        self.rbnDrive.setObjectName("rbnDrive")
        self.grpIsoMode.addButton(self.rbnDrive)
        self.horizontalLayout_5.addWidget(self.rbnDrive)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.rbnDepart = QtWidgets.QRadioButton(self.groupBox_5)
        self.rbnDepart.setObjectName("rbnDepart")
        self.grpIsoSens = QtWidgets.QButtonGroup(QIsoValDockBase)
        self.grpIsoSens.setObjectName("grpIsoSens")
        self.grpIsoSens.addButton(self.rbnDepart)
        self.horizontalLayout_10.addWidget(self.rbnDepart)
        self.rbnArrival = QtWidgets.QRadioButton(self.groupBox_5)
        self.rbnArrival.setObjectName("rbnArrival")
        self.grpIsoSens.addButton(self.rbnArrival)
        self.horizontalLayout_10.addWidget(self.rbnArrival)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.chkToll = QtWidgets.QCheckBox(self.groupBox_6)
        self.chkToll.setObjectName("chkToll")
        self.horizontalLayout_8.addWidget(self.chkToll)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.chkBridge = QtWidgets.QCheckBox(self.groupBox_6)
        self.chkBridge.setObjectName("chkBridge")
        self.horizontalLayout_7.addWidget(self.chkBridge)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.chkTunnel = QtWidgets.QCheckBox(self.groupBox_6)
        self.chkTunnel.setObjectName("chkTunnel")
        self.horizontalLayout_9.addWidget(self.chkTunnel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.mColorButton = QgsColorButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mColorButton.sizePolicy().hasHeightForWidth())
        self.mColorButton.setSizePolicy(sizePolicy)
        self.mColorButton.setMinimumSize(QtCore.QSize(36, 16))
        self.mColorButton.setMaximumSize(QtCore.QSize(36, 16777215))
        self.mColorButton.setObjectName("mColorButton")
        self.horizontalLayout_6.addWidget(self.mColorButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.mColorButton_2 = QgsColorButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mColorButton_2.sizePolicy().hasHeightForWidth())
        self.mColorButton_2.setSizePolicy(sizePolicy)
        self.mColorButton_2.setMinimumSize(QtCore.QSize(36, 16))
        self.mColorButton_2.setMaximumSize(QtCore.QSize(36, 16777215))
        self.mColorButton_2.setObjectName("mColorButton_2")
        self.horizontalLayout_11.addWidget(self.mColorButton_2)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_11.addWidget(self.doubleSpinBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.btnLaunch = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnLaunch.setObjectName("btnLaunch")
        self.horizontalLayout_4.addWidget(self.btnLaunch)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.btnExport = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout_4.addWidget(self.btnExport)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pgbProcess = QtWidgets.QProgressBar(self.dockWidgetContents)
        self.pgbProcess.setProperty("value", 24)
        self.pgbProcess.setObjectName("pgbProcess")
        self.verticalLayout.addWidget(self.pgbProcess)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        QIsoValDockBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(QIsoValDockBase)
        QtCore.QMetaObject.connectSlotsByName(QIsoValDockBase)
        QIsoValDockBase.setTabOrder(self.edtAdd, self.btnPos)
        QIsoValDockBase.setTabOrder(self.btnPos, self.rbnIsochron)
        QIsoValDockBase.setTabOrder(self.rbnIsochron, self.rbnIsoDistance)
        QIsoValDockBase.setTabOrder(self.rbnIsoDistance, self.sbxHour)
        QIsoValDockBase.setTabOrder(self.sbxHour, self.sbxMinute)
        QIsoValDockBase.setTabOrder(self.sbxMinute, self.rbnDrive)
        QIsoValDockBase.setTabOrder(self.rbnDrive, self.chkToll)
        QIsoValDockBase.setTabOrder(self.chkToll, self.chkBridge)
        QIsoValDockBase.setTabOrder(self.chkBridge, self.chkTunnel)

    def retranslateUi(self, QIsoValDockBase):
        _translate = QtCore.QCoreApplication.translate
        QIsoValDockBase.setWindowTitle(_translate("QIsoValDockBase", "Carte isochrone/isodistance"))
        self.groupBox.setTitle(_translate("QIsoValDockBase", "Paramètres généraux"))
        self.label.setText(_translate("QIsoValDockBase", "Adresse de départ :"))
        self.btnPos.setText(_translate("QIsoValDockBase", "Position"))
        self.label_10.setText(_translate("QIsoValDockBase", "Type de carte :"))
        self.rbnIsochron.setText(_translate("QIsoValDockBase", "Isochrone"))
        self.rbnIsoDistance.setText(_translate("QIsoValDockBase", "Isodistance"))
        self.groupBox_3.setTitle(_translate("QIsoValDockBase", "Étendue de la recherche"))
        self.label_4.setText(_translate("QIsoValDockBase", "Temps :"))
        self.label_7.setText(_translate("QIsoValDockBase", "h"))
        self.label_8.setText(_translate("QIsoValDockBase", "min"))
        self.label_5.setText(_translate("QIsoValDockBase", "Distance :"))
        self.label_6.setText(_translate("QIsoValDockBase", "km"))
        self.groupBox_5.setTitle(_translate("QIsoValDockBase", "Paramètres de parcours"))
        self.label_3.setText(_translate("QIsoValDockBase", "Mode de transport :"))
        self.rbnWalk.setText(_translate("QIsoValDockBase", "Piéton"))
        self.rbnDrive.setText(_translate("QIsoValDockBase", "Voiture"))
        self.label_9.setText(_translate("QIsoValDockBase", "Sens de parcours :"))
        self.rbnDepart.setText(_translate("QIsoValDockBase", "Départ"))
        self.rbnArrival.setText(_translate("QIsoValDockBase", "Arrivée"))
        self.groupBox_6.setTitle(_translate("QIsoValDockBase", "Passages autorisés"))
        self.chkToll.setText(_translate("QIsoValDockBase", "Péages"))
        self.chkBridge.setText(_translate("QIsoValDockBase", "Ponts"))
        self.chkTunnel.setText(_translate("QIsoValDockBase", "Tunnels"))
        self.groupBox_2.setTitle(_translate("QIsoValDockBase", "Paramètres de symbologie"))
        self.label_2.setText(_translate("QIsoValDockBase", "Couleur de remplissage :"))
        self.label_11.setText(_translate("QIsoValDockBase", "Couleur de trait :"))
        self.label_12.setText(_translate("QIsoValDockBase", "Largeur de trait (mm) :"))
        self.btnLaunch.setText(_translate("QIsoValDockBase", "Lancer le calcul"))
        self.btnExport.setText(_translate("QIsoValDockBase", "Exporter le résultat"))

from qgscolorbutton import QgsColorButton
